spring:
  # 增加数据库连接
  datasource:
    url: jdbc:mysql://192.168.129.142:3306/course?characterEncoding=UTF8&autoReconnect=true
    username: course
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.hd.course.server.mapper: trace