spring:
  application:
    name: system
  # 增加数据库连接
  datasource:
    url: jdbc:mysql://192.168.129.142:3306/course?characterEncoding=UTF8&autoReconnect=true
    username: course
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9001
  servlet:
    context-path: /system
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.hd.course.system.mapper: trace